routes:
  /getFirstQuestion: Controller\Actions\GetFirstQuestion
  /getNextQuestion: Controller\Actions\GetNextQuestion
  /getAllQuestions: Controller\Actions\GetAllQuestions
  /answerQuestion: Controller\Actions\AnswerQuestion